const {test}=require('node:test');const assert=require('node:assert/strict');const T=require('../web/transfer.js');
test('original clipboard keeps saved amounts and empty final notes',()=>{const e=T.decode('קטגוריה\tתאריך\tשעות\tתעריף שעתי\tשכר לתשלום\tסטטוס\tהערות\nעבודה\t26/03/2026\t5.8\t40\t233.33\tשולם\t').entries[0];assert.equal(e.totalEarnings,233.33);assert.equal(e.notes,'');assert.equal(new Date(e.date).getMonth(),2);});
test('CSV round trip keeps dates, currency and quoted multiline notes',()=>{const e=T.decode('category,date,hours,rate,total,paid,notes,currency\nWork,2026-09-07,2,50,99,true,"one, two\nthree ""quoted""",USD').entries;assert.deepEqual(T.decode(T.csv(e)).entries,e);});
test('Excel serial and decimal comma',()=>{const e=T.decode('category;date;hours;rate;total\nWork;45000;2:30;50,5;126,25').entries[0];assert.equal(e.hours,2.5);assert.equal(e.hourlyRate,50.5);});
test('invalid date, unknown status and duplicate columns reject entire input',()=>{for(const s of ['category,date,hours,rate\nWork,31/02/2026,2,50','category,date,hours,rate,paid\nWork,2026-09-07,2,50,maybe','category,date,hours,rate,rate\nWork,2026-09-07,2,50,60'])assert.throws(()=>T.decode(s));});
test('multiset duplicate protection retains genuine repeated rows',()=>{const e=T.decode('category,date,hours,rate\nWork,2026-09-07,2,50').entries[0];assert.equal(T.missing([e],[e,e]).length,1);assert.equal(T.missing([e,e],[e,e]).length,0);});
test('JSON group metadata and category decimals survive',()=>{const base=T.decode('category,date,hours,rate\nWork,2026-09-07,2,50').entries[0];const root={formatVersion:2,entries:[{...base,isGroupShift:true,employerRate:70,workerRate:50,groupWorkersJson:'[{"name":"A","hours":2,"isPaid":true}]'}],categories:[{name:'Work',defaultRate:50.5}],workers:[{name:'A'}]};assert.deepEqual(T.decode(JSON.stringify(root)),root);});
test('currencies are never combined',()=>{assert.deepEqual(T.totals([{currency:'₪',totalEarnings:100},{currency:'$',totalEarnings:20}]),{'₪':100,'$':20});});
test('ambiguous and negative numbers require correction',()=>{assert.throws(()=>T.number('1,234'));assert.throws(()=>T.number('-50'));});

test('Excel clipboard TSV preserves columns and quoted multiline notes',()=>{const entries=T.decode('category,date,hours,rate,notes\nWork,2026-09-07,2,50,"one, two\nthree"').entries;const tsv=T.csv(entries,'\t');assert.ok(tsv.startsWith('\ufeffcategory\tdate\thours'));assert.deepEqual(T.decode(tsv).entries,entries);});
