// RC13 release-critical flows, disposable browser contexts and synthetic fixtures only.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=path.resolve('public'),out=process.env.SCREENSHOT_DIR||'browser-evidence';fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!target.startsWith(root+path.sep)||!fs.existsSync(target)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',target.endsWith('.js')?'application/javascript':target.endsWith('.css')?'text/css':target.endsWith('.ttf')?'font/ttf':'text/html');res.end(fs.readFileSync(target));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});
 const errors=[];const context=async(width,height,seed)=>{const c=await browser.newContext({viewport:{width,height},locale:'he-IL',hasTouch:width<600,isMobile:width<600});await c.route('https://www.gstatic.com/**',r=>r.abort());if(seed)await c.addInitScript(data=>{if(location.protocol==='http:'&&!sessionStorage.getItem('seeded')){for(const [k,v] of Object.entries(data))localStorage.setItem(k,v);sessionStorage.setItem('seeded','yes');}},seed);c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));return c;};
 const bounds=async p=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await p.evaluate(()=>document.documentElement.dir),'rtl');};
 try{
 for(const width of [360,390,768,1440]){
  const c=await context(width,844),p=await c.newPage();await p.goto(url,{waitUntil:'domcontentloaded'});
  assert.equal(await p.locator('#tutorial-dialog').isVisible(),true);assert.match(await p.locator('#tutorial-progress').innerText(),/1 מתוך 9/);
  for(let i=1;i<9;i++){await p.getByRole('button',{name:'הבא',exact:true}).click();await bounds(p);assert.match(await p.locator('#tutorial-progress').innerText(),new RegExp((i+1)+' מתוך 9'));if(i===2&&width===390)await p.screenshot({path:path.join(out,'tutorial-390.png')});}
  await p.getByRole('button',{name:'מתחילים',exact:true}).click();assert.equal(await p.locator('#tutorial-dialog').isVisible(),false);assert.equal(await p.evaluate(()=>localStorage.getItem('work_complete_backup')),null);await bounds(p);
  if([360,390,1440].includes(width))await p.screenshot({path:path.join(out,'home-'+width+'.png')});
  await p.getByRole('button',{name:'דיווח חדש',exact:true}).click();await bounds(p);
  const date=await p.locator('#modal-date').boundingBox(),start=await p.locator('#modal-start').boundingBox(),end=await p.locator('#modal-end').boundingBox();assert.equal(date.y,start.y);assert.equal(start.y,end.y);
  await p.locator('#modal-notes').fill('טיוטה '+width);await p.reload({waitUntil:'domcontentloaded'});assert.equal(await p.locator('#modal-notes').inputValue(),'טיוטה '+width);
  if([360,390,1440].includes(width))await p.screenshot({path:path.join(out,'form-'+width+'.png')});
  await p.getByRole('button',{name:'ניהול וקטגוריות',exact:true}).click();await p.getByRole('button',{name:'הצג שוב את ההדרכה',exact:true}).click();await p.getByRole('button',{name:'דלג',exact:true}).click();await p.locator('#settings-dialog').getByRole('button',{name:'ביטול',exact:true}).click();assert.equal(await p.locator('#modal-notes').inputValue(),'טיוטה '+width);
  await p.locator('#modal-start').fill('22:00');await p.locator('#modal-end').fill('02:00');await p.locator('#modal-break').fill('30');await p.locator('#modal-rate').fill('20');await p.locator('#modal-currency').selectOption('$');await p.getByRole('button',{name:'שמירה',exact:true}).click();
  let data=await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')));assert.equal(data.entries[0].hours,3.5);assert.equal(data.entries[0].totalEarnings,70);assert.equal(data.entries[0].currency,'$');assert.equal(await p.locator('#report-content').isVisible(),false);
  assert.equal(await p.locator('.summary-card').count(),2);assert.match(await p.locator('.summary-card').nth(1).innerText(),/סיכום בדולרים/);
  await p.getByRole('button',{name:'היסטוריה',exact:true}).click();assert.match(p.url(),/#history$/);await p.goBack();assert.equal(await p.locator('#page-home').isVisible(),true);await p.goForward();assert.equal(await p.locator('#page-history').isVisible(),true);
  await p.getByRole('button',{name:'סינון',exact:true}).click();await p.getByRole('button',{name:'ממתין',exact:true}).click();await p.getByRole('button',{name:'טווח מותאם',exact:true}).click();await p.locator('#date-from').fill('2026-01-01');await p.locator('#date-to').fill('2026-12-31');await p.getByRole('button',{name:'הצג תוצאות',exact:true}).click();assert.equal(await p.locator('#shifts-list .journal-card').count(),1);
  await p.getByRole('button',{name:'בחירת משמרות',exact:true}).click();await p.getByRole('button',{name:'בחר הכל',exact:true}).click();assert.match(await p.locator('#selection-total').innerText(),/\$ 70.00/);await bounds(p);await p.getByRole('button',{name:'סיום בחירה',exact:true}).click();
  if([360,390,1440].includes(width))await p.screenshot({path:path.join(out,'history-'+width+'.png')});
  await p.getByRole('button',{name:'ראשי',exact:true}).click();await p.getByRole('button',{name:'התחל משמרת פעילה',exact:true}).click();await p.locator('#live-rate').fill('25.5');await p.locator('#live-currency').selectOption('$');await p.getByRole('button',{name:'התחל משמרת',exact:true}).click();
  await p.evaluate(()=>{const key='work_active_shift_v1:guest',t=JSON.parse(localStorage.getItem(key));t.startedAt=Date.now()-2.5*3600000;localStorage.setItem(key,JSON.stringify(t));});await p.reload({waitUntil:'domcontentloaded'});assert.match(await p.locator('#active-shift-timer').innerText(),/02:30:/);assert.match(await p.locator('#active-shift-amount').innerText(),/\$63.75/);
  await p.getByRole('button',{name:'סיים משמרת פעילה',exact:true}).click();await p.getByRole('button',{name:'כן, סיים',exact:true}).click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('work_complete_backup')).entries.length===2);data=await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')));assert.equal(data.entries.length,2);assert.equal(data.entries[0].currency,'$');assert.ok(Math.abs(data.entries[0].totalEarnings-63.75)<.03);assert.equal(await p.evaluate(()=>localStorage.getItem('work_active_shift_v1:guest')),null);
  if(width===390){await p.getByRole('button',{name:'ניהול וקטגוריות',exact:true}).click();await p.locator('#settings-dialog summary').filter({hasText:'ניהול עבודה וקטגוריות'}).click();await p.screenshot({path:path.join(out,'settings-390.png')});await p.locator('#settings-dialog').getByRole('button',{name:'ביטול',exact:true}).click();await p.waitForFunction(()=>navigator.serviceWorker.controller!==null);await c.setOffline(true);await p.reload({waitUntil:'domcontentloaded'});assert.equal(await p.locator('#page-home').isVisible(),true);assert.equal((await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')))).entries.length,2);await c.setOffline(false);}
  await c.close();console.log('PASS: fresh/tutorial/replay/compact fields/draft/overnight/USD/selection/filter/back-forward/timer/reload '+width+'px');
 }
 const entries=Array.from({length:22},(_,i)=>({id:'existing-'+i,category:'קטגוריה '+(i%8),date:new Date(2026,8,1+i).getTime(),createdAt:100+i,hours:2.25,hourlyRate:35.5,totalEarnings:90.17+i,currency:i%2?'$':'₪',isPaid:i%2===0,notes:'מקורי '+i,isGroupShift:i===0,groupWorkersJson:i===0?'[{"name":"בדיקה","hours":3,"workerRate":17.25,"employerRate":29,"isPaid":true}]':'',customExtension:'preserve-'+i}));
 const cats=Array.from({length:8},(_,i)=>({name:'קטגוריה '+i,defaultRate:35.5})),snapshot=JSON.stringify({entries,categories:cats,workers:[{name:'בדיקה'}],webPreferences:{mainCurrency:'$',defaultCategory:'קטגוריה 3',categoryCurrencies:{'קטגוריה 3':'$'}}});
 for(const seed of [{work_complete_backup:snapshot},{user_work_shifts:JSON.stringify(entries),work_transfer_meta:JSON.stringify({categories:cats,workers:[{name:'בדיקה'}]}),work_default_currency:'$'}]){
  const c=await context(390,844,seed),p=await c.newPage();await p.goto(url,{waitUntil:'domcontentloaded'});assert.equal(await p.locator('#tutorial-dialog').isVisible(),false);assert.deepEqual(await p.evaluate(()=>shifts),entries);
  const snapshotBytes=await p.evaluate(()=>localStorage.getItem('work_complete_backup'));if(seed.work_complete_backup)assert.equal(snapshotBytes,snapshot);
  await p.getByRole('button',{name:'היסטוריה',exact:true}).click();await p.locator('#shifts-list summary').first().click();await p.locator('#shifts-list .journal-card').first().getByRole('button',{name:'עריכה',exact:true}).click();await p.locator('#modal-notes').fill('שינוי מטאדאטה');await p.locator('#add-modal').getByRole('button',{name:'שמירה',exact:true}).click();await p.reload({waitUntil:'domcontentloaded'});
  const after=await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')));assert.equal(after.entries.length,22);assert.equal(after.categories.length,8);assert.equal(after.entries[0].totalEarnings,entries[0].totalEarnings);assert.equal(after.entries[0].groupWorkersJson,entries[0].groupWorkersJson);assert.equal(after.entries[0].customExtension,'preserve-0');assert.ok(await p.evaluate(()=>localStorage.getItem('work_pre_rc13_snapshot_v1')));await c.close();console.log('PASS: existing 22/8 financial data, worker metadata, custom extensions and edit/reload from '+Object.keys(seed)[0]);
 }
 assert.deepEqual(errors,[]);console.log('PASS: no application JavaScript errors; offline reload; RTL, mobile/tablet/desktop; synthetic data only.');
 }catch(e){console.error(e);throw e;}finally{await browser.close();server.close();}
})().catch(()=>process.exitCode=1);
