// RC15 feature parity, real DOM/keyboard and disposable synthetic local data.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=path.resolve('public'),out=process.env.SCREENSHOT_DIR||'browser-evidence';fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.ttf')?'font/ttf':'text/html');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox'],headless:true});
 const errors=[];
 try{for(const width of [360,390,768,1440]){
  const context=await browser.newContext({viewport:{width,height:844},locale:'he-IL'});
  await context.route('https://www.gstatic.com/**',r=>r.abort());
  await context.route('**/_vercel/insights/**',r=>r.abort());
  await context.addInitScript(()=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem('work_onboarding_version','1');localStorage.setItem('work_complete_backup',JSON.stringify({formatVersion:2,entries:[],workers:[],categories:[{name:'ללא מטבע',defaultRate:37},{name:'שקל מפורש',defaultRate:20}],webPreferences:{mainCurrency:'$',defaultCategory:'ללא מטבע',categoryCurrencies:{'שקל מפורש':'₪'}}}));sessionStorage.setItem('seeded','yes');}});
  const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.PUBLIC_SITE_URL||('http://127.0.0.1:'+server.address().port),{waitUntil:'domcontentloaded'});
  await p.getByRole('button',{name:'ניהול וקטגוריות',exact:true}).click();await p.locator('.main-currency-settings > summary').click();assert.match(await p.locator('#default-category-button').innerText(),/ללא מטבע/);
  await p.locator('#default-category-button').click();await p.locator('#default-category-options').getByRole('button',{name:'שקל מפורש',exact:true}).click();assert.match(await p.locator('#default-category-button').innerText(),/שקל מפורש/);
  await p.locator('#default-category-button').click();await p.locator('#default-category-dialog').getByRole('button',{name:'הוספת קטגוריה',exact:true}).click();await p.locator('#category-name').fill('חדש '+width);assert.equal(await p.locator('#category-currency').inputValue(),'$');assert.equal(await p.locator('#category-default').isChecked(),true);
  const rate=await p.locator('#category-rate').boundingBox(),money=await p.locator('#category-currency').boundingBox();assert.ok(Math.abs(rate.y-money.y)<2);await p.locator('#category-dialog').getByRole('button',{name:'שמירה',exact:true}).click();assert.match(await p.locator('#default-category-button').innerText(),new RegExp('חדש '+width));
  await p.screenshot({path:path.join(out,'rc15-default-'+width+'.png')});
  // Cancel the settings draft: new category/default must not leak into saved data.
  await p.locator('#settings-dialog').getByRole('button',{name:'ביטול',exact:true}).click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')).categories.length),2);
  await p.getByRole('button',{name:'התחל משמרת פעילה',exact:true}).click();assert.equal(await p.locator('#live-currency').inputValue(),'$');
  const liveRate=await p.locator('#live-rate').boundingBox(),liveMoney=await p.locator('#live-currency').boundingBox();assert.ok(Math.abs(liveRate.y-liveMoney.y)<2);
  await p.locator('#live-shift-dialog').getByRole('button',{name:'התחל משמרת',exact:true}).click();const timer=await p.evaluate(()=>WorkRuntime.readTimer(localStorage,null));
  await p.locator('#active-shift-currency').selectOption('₪');let changed=await p.evaluate(()=>WorkRuntime.readTimer(localStorage,null));assert.deepEqual(changed,{...timer,currency:'₪'});await p.reload({waitUntil:'domcontentloaded'});assert.equal(await p.locator('#active-shift-currency').inputValue(),'₪');
  await p.getByRole('button',{name:'בטל משמרת פעילה',exact:true}).click();assert.equal(await p.locator('#confirm-dialog').isVisible(),true);await p.locator('#confirm-dialog').getByRole('button',{name:'ביטול',exact:true}).click();assert.deepEqual(await p.evaluate(()=>WorkRuntime.readTimer(localStorage,null)),changed);
  await p.getByRole('button',{name:'בטל משמרת פעילה',exact:true}).click();await p.locator('#confirm-dialog').getByRole('button',{name:'כן, בטל משמרת',exact:true}).click();await p.waitForFunction(()=>WorkRuntime.readTimer(localStorage,null)===null);assert.equal(await p.evaluate(()=>WorkRuntime.readTimer(localStorage,null)),null);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')).entries.length),0);
  // A new timer replaces one awaiting confirmation: confirmation cannot discard it.
  await p.getByRole('button',{name:'התחל משמרת פעילה',exact:true}).click();await p.locator('#live-category').selectOption('שקל מפורש');assert.equal(await p.locator('#live-currency').inputValue(),'₪');await p.locator('#live-shift-dialog').getByRole('button',{name:'התחל משמרת',exact:true}).click();await p.getByRole('button',{name:'בטל משמרת פעילה',exact:true}).click();await p.evaluate(()=>{const t=WorkRuntime.readTimer(localStorage,null);localStorage.setItem(WorkRuntime.timerKey(null),JSON.stringify({...t,id:'replacement'}));});await p.locator('#confirm-dialog').getByRole('button',{name:'כן, בטל משמרת',exact:true}).click();assert.equal(await p.evaluate(()=>WorkRuntime.readTimer(localStorage,null).id),'replacement');
  await p.locator('#active-shift-currency').selectOption('$');await p.evaluate(()=>{const t=WorkRuntime.readTimer(localStorage,null);localStorage.setItem(WorkRuntime.timerKey(null),JSON.stringify({...t,startedAt:Date.now()-3600000}));});await p.getByRole('button',{name:'סיים משמרת פעילה',exact:true}).click();await p.locator('#confirm-dialog').getByRole('button',{name:'כן, סיים',exact:true}).click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('work_complete_backup')).entries.some(e=>e.id==='replacement'));const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('work_complete_backup')).entries[0]);assert.equal(saved.currency,'$');assert.ok(saved.hours>=1);assert.equal(saved.id,'replacement');
  await p.getByRole('button',{name:'ניהול וקטגוריות',exact:true}).click();await p.locator('#system-settings > summary').click();await p.locator('#feedback-message').fill('שורה ראשונה');await p.locator('#feedback-message').press('End');await p.locator('#feedback-message').press('Enter');await p.locator('#feedback-message').pressSequentially('שורה שנייה');assert.equal(await p.locator('#feedback-message').inputValue(),'שורה ראשונה\nשורה שנייה');assert.equal(await p.locator('#settings-dialog').isVisible(),true);assert.equal(await p.locator('#system-settings').getAttribute('open'),'');
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.join(out,'rc15-feedback-'+width+'.png')});await context.close();
 }assert.deepEqual(errors,[]);console.log('RC15 defaults/add/cancel draft, USD fallback/explicit override, active currency/reload/confirmed cancel/stale guard/finish, Enter and 4 widths passed');}
 finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1);});
