let historyPeriod='all',historyCurrency='הכל',historySort='newest',displayedEntries=[];
const iconPaths={
 copy:'M16 1H4a2 2 0 0 0-2 2v14h2V3h12zm4 4H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2m0 16H8V7h12z',
 sort:'M3 6h18v2H3zm0 5h12v2H3zm0 5h6v2H3z',
 label:'M17.6 5H3v14h14.6l5-7zM16.6 17H5V7h11.6l3.5 5z',
 cash:'M2 4h18v14H2zm2 2v10h14V6zm8 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m10-3v12H6v2h18V8z',
 timer:'M9 1h6v2H9zm3 3a9 9 0 1 0 6.3 2.6L20 5l-1.4-1.4L17 5.2A9 9 0 0 0 12 4m0 2a7 7 0 1 1 0 14 7 7 0 0 1 0-14m-1 2h2v6h-2z',
 down:'M7 9l5 5 5-5 1.4 1.4L12 16.8l-6.4-6.4z',
 edit:'M3 17.3V21h3.7L17.8 9.9l-3.7-3.7zM20.7 7c.4-.4.4-1 0-1.4l-2.3-2.3a1 1 0 0 0-1.4 0l-1.8 1.8 3.7 3.7z',
 trash:'M6 19a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7H6zm2-10h8v10H8zm7-6-1-1h-4L9 3H4v2h16V3z',
 check:'M9 16.2 4.8 12 3.4 13.4 9 19 21 7l-1.4-1.4z'
};
function uiIcon(name){return '<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="'+iconPaths[name]+'"/></svg>';}
function initParity(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=uiIcon(el.dataset.icon));const def=localStorage.getItem('work_default_currency');if(['₪','$'].includes(def))document.getElementById('modal-currency').value=def;document.querySelectorAll('#settings-dialog details').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)document.querySelectorAll('#settings-dialog details').forEach(other=>{if(other!==el)other.open=false;});}));}
function openWebSettings(){document.getElementById('default-currency').value=localStorage.getItem('work_default_currency')||'₪';document.getElementById('settings-dialog').showModal();}
function saveWebSettings(){try{const value=document.getElementById('default-currency').value;localStorage.setItem('work_default_currency',value);if(editingShiftId===null)document.getElementById('modal-currency').value=value;document.getElementById('settings-dialog').close();showMessage('ההגדרות נשמרו');}catch{showMessage('לא ניתן לשמור את ההגדרות');}}
function openHistorySearch(){showPage(1);document.getElementById('history-search').hidden=false;document.getElementById('search-box').focus();}
function setPeriod(period){historyPeriod=period;document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('selected',b.dataset.period===period));document.getElementById('period-inputs').hidden=period==='all';document.getElementById('month-label').hidden=period!=='month';document.getElementById('from-label').hidden=period!=='range';document.getElementById('to-label').hidden=period!=='range';renderShifts();}
function setPayment(value){document.getElementById('payment-filter').value=value;document.querySelectorAll('[data-payment]').forEach(b=>b.classList.toggle('selected',b.dataset.payment===value));renderShifts();}
function cycleCurrency(){historyCurrency=historyCurrency==='הכל'?'₪':historyCurrency==='₪'?'$':'הכל';document.getElementById('currency-filter').textContent=historyCurrency;renderShifts();}
function setSort(value){historySort=value;document.getElementById('sort-dialog').close();renderShifts();}
function renderHistoryControls(entries){document.getElementById('journal-title').textContent='יומן עבודה ('+entries.length+')';document.getElementById('displayed-total').textContent=formatTotals(WorkTransfer.totals(entries));const select=document.getElementById('category-filter');select.replaceChildren();for(const name of ['הכל',...new Set([...categories.map(c=>c.name),...shifts.map(s=>s.category)])]){const o=document.createElement('option');o.value=name;o.textContent=name==='הכל'?'כל הקטגוריות':name;select.append(o);}select.value=selectedCategory;}
async function copyDisplayed(kind){const text=kind==='table'?WorkTransfer.csv(displayedEntries):displayedEntries.map(e=>new Date(e.date).toLocaleDateString('he-IL')+' · '+e.category+' · '+e.hours+' שעות · '+e.currency+' '+e.totalEarnings.toFixed(2)+' · '+(e.isPaid?'שולם':'ממתין')).join('\n')+'\nסה״כ: '+formatTotals(WorkTransfer.totals(displayedEntries));try{await navigator.clipboard.writeText(text);document.getElementById('report-dialog').close();showMessage('הדוח הועתק');}catch{showMessage('הדפדפן לא אפשר העתקה. אפשר לייצא קובץ דרך ההגדרות.');}}
function createShiftCard(entry,compact=false){
 const card=document.createElement('details');card.className='journal-card'+(compact?' compact':'');
 const summary=document.createElement('summary');const date=new Date(entry.date).toLocaleDateString('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});
 summary.innerHTML='<span class="category-avatar">'+escapeHtml(entry.category.slice(0,1))+'</span><span class="journal-info"><b>'+(!compact?uiIcon('label'):'')+escapeHtml(entry.category)+'</b><small>'+date+'</small></span><span class="journal-amount"><b>'+(!compact?uiIcon('cash'):'')+'<bdi>'+escapeHtml(entry.currency)+Number(entry.totalEarnings).toFixed(compact?1:2)+'</bdi></b><small>'+(!compact?uiIcon('timer'):'')+Number(entry.hours).toFixed(1)+' ש׳ <i class="status-dot '+(entry.isPaid?'paid':'')+'" title="'+(entry.isPaid?'שולם':'ממתין')+'"></i></small></span><span class="chevron">'+uiIcon('down')+'</span>';
 const body=document.createElement('div');body.className='journal-details';const p=document.createElement('p');p.textContent=(entry.isTimeRange?entry.startTime+' – '+entry.endTime+' · ':'')+entry.hours+' שעות · '+entry.hourlyRate+' '+entry.currency+' לשעה';body.append(p);if(entry.notes){const notes=document.createElement('p');notes.textContent=entry.notes;body.append(notes);}
 if(entry.isGroupShift){try{const members=JSON.parse(entry.groupWorkersJson||'[]');const heading=document.createElement('h3');heading.textContent='עבודה קבוצתית';body.append(heading);let hours=0;for(const worker of members){hours+=Number(worker.hours);const line=document.createElement('p');line.textContent=worker.name+' · '+worker.hours+' שעות · '+(worker.isPaid?'שולם':'ממתין');body.append(line);}const total=document.createElement('p');total.textContent='כולל עובדים לתשלום: '+entry.currency+' '+(entry.totalEarnings+hours*(entry.employerRate??0)).toFixed(2)+' · השכר שלי כולל הפרש תעריפים: '+entry.currency+' '+(entry.totalEarnings+hours*((entry.employerRate??0)-(entry.workerRate??0))).toFixed(2);body.append(total);}catch{const p=document.createElement('p');p.textContent='לא ניתן להציג את פרטי הקבוצה. הנתונים נשמרו ללא שינוי.';body.append(p);}}
 const actions=document.createElement('div');actions.className='journal-card-actions';for(const [name,label,action] of [['check',entry.isPaid?'סמן כממתין':'סמן כשולם',()=>togglePaid(entry.id)],['edit','עריכה',()=>editShift(entry.id)],['trash','מחיקה',()=>deleteShift(entry.id)]]){const button=document.createElement('button');button.className='btn-mini';button.innerHTML=uiIcon(name)+'<span>'+label+'</span>';button.onclick=action;actions.append(button);}body.append(actions);card.append(summary,body);return card;
}
